Introduction
------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.

.. toctree::
   :maxdepth: 2

   introduction
   community
   resources


Getting Started
---------------

This part of the guide focuses on setting up your Python environment.

.. toctree::
   :maxdepth: 2

   which-python
   installation
   dev-env
   getting-started-next


Writing Great Code
------------------

This part of the guide focuses on best practices for writing Python code.

.. toctree::
   :maxdepth: 2

   project-structure
   code-style
   documentation
   testing
   packaging



Shipping Great Code
-------------------

This part of the guide focuses on deploying your Python code.

.. toctree::
   :maxdepth: 2

   project-structure
   documentation
   testing
   packaging
   freezing



Additional Notes
----------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   contribute
   license