Introduction
------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/resources


Getting Started
---------------

This part of the guide focuses on setting up your Python environment.

.. toctree::
   :maxdepth: 2

   starting/which-python
   starting/installation
   starting/dev-env
   starting/next


Writing Great Code
------------------

This part of the guide focuses on best practices for writing Python code.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   starting/documentation
   starting/tests



Shipping Great Code
-------------------

This part of the guide focuses on deploying your Python code.

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


Scenario Guide
--------------

This part of the guide focuses on tool and module advice based on
different scenarios.

.. toctree::
   :maxdepth: 2

   scenarios/web
   scenarios/admin
   scenarios/ci



Additional Notes
----------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license